language: ruby
sudo: false
cache: bundler

script: "bundle exec rake"

services: mongodb
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-head
  - jruby
  - rbx-2
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby-head
    - gemfile: gemfiles/rails_edge.gemfile

